<Project>
  <!-- Normalize $(TestWpfArcadeSdkPath) by appending a '\' to it if one is missing -->
  <PropertyGroup Condition="'$(TestWpfArcadeSdkPath)'!=''">
    <WpfArcadeSdkPath>$(TestWpfArcadeSdkPath)</WpfArcadeSdkPath>
    <WpfArcadeSdkPath Condition="!$(WpfArcadeSdkPath.EndsWith('\'))">$(TestWpfArcadeSdkPath)\</WpfArcadeSdkPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestWpfArcadeSdkPath)'=='' And Exists('$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\')">
    <WpfArcadeSdkPath>$(MSBuildThisFileDirectory)eng\WpfArcadeSdk\</WpfArcadeSdkPath>
  </PropertyGroup>
  <!-- Select Sdk.props from test location or eng\WpfArcadeSdk\. If neither exists, then fall back to the use of one 
      obtained using MSBuild's Sdk resolver -->
  <PropertyGroup Condition="Exists('$(WpfArcadeSdkPath)')">
    <WpfArcadeSdkProps>$(WpfArcadeSdkPath)Sdk\Sdk.props</WpfArcadeSdkProps>
    <WpfArcadeSdkTargets>$(WpfArcadeSdkPath)Sdk\Sdk.targets</WpfArcadeSdkTargets>
  </PropertyGroup>
  
  <PropertyGroup>
  <NuGetAudit>false</NuGetAudit>
</PropertyGroup>
  
  <Import Project="$(WpfArcadeSdkProps)"
          Condition="Exists('$(WpfArcadeSdkProps)') And Exists('$(WpfArcadeSdkTargets)')"/>

  <Import Sdk="Microsoft.DotNet.Arcade.Wpf.Sdk"
          Project="Sdk.props"
          Condition="!Exists('$(WpfArcadeSdkProps)') Or !Exists('$(WpfArcadeSdkTargets)')"/>
  
  <PropertyGroup>
    <WpfTestsRoot>$(MsBuildThisFileDirectory)</WpfTestsRoot>
    <BinariesRoot>$(WpfTestsRoot)bin\</BinariesRoot>
    <PublishRoot>$(WpfTestsRoot)publish\</PublishRoot>
    <ObjRoot>$(BinariesRoot)obj\</ObjRoot>
    <PackagesRoot>$(BinariesRoot)packages\</PackagesRoot>
    <PlatformFolder>x86</PlatformFolder>
    <PlatformFolder Condition="'$(Platform)' == 'x64'">x64</PlatformFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Remove="PresentationCore" />
    <Reference Remove="PresentationFramework" />
    <Reference Remove="PresentationFramework-SystemCore" />
    <Reference Remove="PresentationFramework-SystemData" />
    <Reference Remove="PresentationFramework-SystemDrawing" />
    <Reference Remove="PresentationFramework-SystemXml" />
    <Reference Remove="PresentationFramework-SystemXmlLinq" />
    <Reference Remove="PresentationFramework.Aero" />
    <Reference Remove="PresentationFramework.Aero2" />
    <Reference Remove="PresentationFramework.AeroLite" />
    <Reference Remove="PresentationFramework.Classic" />
    <Reference Remove="PresentationFramework.Luna" />
    <Reference Remove="PresentationFramework.Royale" />
    <Reference Remove="PresentationUI" />
    <Reference Remove="ReachFramework" />
    <Reference Remove="System.Printing" />
    <Reference Remove="System.Windows.Controls.Ribbon" />
    <Reference Remove="System.Windows.Input.Manipulations" />
    <Reference Remove="System.Windows.Presentation" />
    <Reference Remove="System.Xaml" />
    <Reference Remove="UIAutomationClient" />
    <Reference Remove="UIAutomationClientSideProviders" />
    <Reference Remove="UIAutomationProvider" />
    <Reference Remove="UIAutomationTypes" />
    <Reference Remove="WindowsBase" />
    <Reference Remove="WindowsFormsIntegration" />
  </ItemGroup>
  
</Project>