<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DrtNGCTest</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>EXE</OutputType>
    <Culture>Neutral</Culture>
    <UnsafeCode>false</UnsafeCode>
    <DefineConstants>NGCTEST</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(DrtCommonRoot)\inc\DrtBase.cs" />
    <Compile Include="DrtNGCSerialization.cs" />
    <None Include="*.xaml">
      <Link>DrtFiles\NGCTest\%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ReachFramework" Condition="'$(TargetFrameworkIdentifier)'!='.NETFramework'" />
    <Reference Include="System.Printing" Condition="'$(TargetFrameworkIdentifier)'!='.NETFramework'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(RepoRoot)build\shared\InjectWpfgfxLoader.cs" Condition="'$(TargetFrameworkIdentifier)'=='.NETFramework'"/>
  </ItemGroup>
</Project>
