<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DrtHyperlinkTargeting</AssemblyName>
    <OutputType>winexe</OutputType>
    <AssemblyAttributeClsCompliant>false</AssemblyAttributeClsCompliant>
  </PropertyGroup>
  <ItemGroup>
    <!-- Aplication markup -->
    <ApplicationDefinition Include="DrtHyperlinkTargetingApp.xaml" />
    <Compile Include="..\..\Logger\Logger.cs" />
    <Compile Include="DrtHyperlinkTargetingApp.xaml.cs" />
    <!-- Compiled Xaml Files list -->
    <Page Include="FramesOne.xaml" />
    <Page Include="Page21.xaml" />
    <Page Include="Page22.xaml" />
    <Page Include="FramesTwo.xaml" />
    <Page Include="PageA.xaml" />
    <Page Include="PageB.xaml" />
  </ItemGroup>

  <UsingTask TaskName="PreloadAssemblyTask"
           AssemblyFile="C:\Code\wpf-test\artifacts\bin\BuildTasksProject\x64\Release\win-x64\BuildTasksProject.dll" />

<Target Name="PreloadUIAutomationTypes" BeforeTargets="MarkupCompilePass1">
  <PreloadAssemblyTask AssemblyPath="C:\Test\WPFDeployment\artifacts\bin\UIAutomationTypes\x64\Release\net481\UIAutomationTypes.dll" />
</Target>



  <ItemGroup Condition ="'$(TargetFrameworkIdentifier)'=='.NETFramework'">
    <Reference Include="UIAutomationTypes">
      <HintPath>$(WpfBinDirectory)UIAutomationTypes\$(Platform)\$(Configuration)\net481\UIAutomationTypes.dll</HintPath>
      <Private>true</Private>
      <SpecificVersion>true</SpecificVersion>
      <EmbedInteropTypes>false</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
</Project>
